global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'inference-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inference-api:8000']

  - job_name: 'airflow-statsd'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'minio'
    metrics_path: '/minio/prometheus/metrics'
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'postgres-airflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']
